config/routes.rb
Rails.application.routes.draw do
  root 'apartments#index'
  
  devise_for :users
  resources :reviews
  resources :users, only: [:index, :show] do
    resources :reviews, only: [:create, :show, :index]
  end
  resources :apartments
  resources :searches, only: [:new, :create, :show]
  resources :followings, only: [:new, :index, :show, :create]
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  mount_uploader :coverphoto, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  has_many :apartments, foreign_key: 'agent_id', class_name: 'Apartment', dependent: :destroy

  # Followings associatons
  # followings initiated by
  has_many :followings, dependent: :destroy, class_name: 'Following', foreign_key: 'follower_id'
  has_many :followers, through: :followings, source: :follower

  # followings initiated by other users
  has_many :inverse_followings, class_name: 'Following', foreign_key: 'followed_id'
  has_many :followeds, through: :followings, source: :followed

  # Reviews
  has_many :reviews, class_name: 'Review', foreign_key: 'reviewer_id'
  has_many :reviewers, through: :reviews, source: :reviewer

  # Reviews created by other users
  has_many :inverse_reviews, class_name: 'Review', foreign_key: 'reviewed_id'
  has_many :revieweds, through: :reviews, source: :reviewed
  accepts_nested_attributes_for :reviews, reject_if: :all_blank, allow_destroy: true

  # file size validations
  validate :avatar_size_validation
  validate :coverphoto_size_validation

  # User Avatar Validation
  validates_integrity_of :avatar
  validates_processing_of :avatar

  # User Cover Photo Validation
  validates_integrity_of :coverphoto
  validates_processing_of :coverphoto

  private

  def avatar_size_validation
    errors[:avatar] << 'should be less than 1000KB(1mb)' if avatar.size > 1.megabytes
  end

  def coverphoto_size_validation
    errors[:coverphoto] << 'should be less than 1000KB(1mb)' if coverphoto.size > 1.megabytes
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def index
    @users = User.all.includes(:reviews, :followings)
  end

  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/user_helper.rb
module UserHelper
  def render_onwner_heading
    if @user == current_user
      content_tag(
        :h2, 'My Apartment Postings',
        class: 'owner-apartments-heading'
      )
    else
      content_tag(
        :h2, "#{@user.fullname.capitalize!}'s Apartment Postings",
        class: 'owner-apartments-heading'
      )
    end
  end

  def render_no_apartments_info(apartments_arr)
    if @user != current_user && !apartments_arr.count.positive?
      content_tag(
        :h2, "#{@user.fullname.capitalize!} has no apartment postings yet",
        class: 'no-apartments-yet owner-apartments-heading'
      )
    elsif @user == current_user && !apartments_arr.count.positive?
      content_tag :div, class: 'no-apartments-yet' do
        content_tag(:h2, 'You have no apartment postings yet', class: 'owner-apartments-heading')
      end
    end
  end

  def render_apartment_details(rental)
    content_tag :div, class: 'apartment-unit-details' do
      item1 = content_tag(:small) do
        content_tag(:span, "Address:  #{rental.address}", class: 'detail-var')
      end

      item2 = content_tag(:small) do
        content_tag(:span, "Category:  #{rental.category}", class: 'detail-var')
      end

      item3 = content_tag(:small) do
        content_tag(:span, "Price(£): #{rental.price}", class: 'detail-var')
      end

      item4 = content_tag(:small) do
        content_tag(:span, "Agent: #{apartment_creator(rental)}", class: 'detail-var')
      end

      item5 = content_tag(:small) do
        link_to('Details', apartment_path(rental), class: 'search-result-details-link')
      end

      item1 + item2 + item3 + item4 + item5
    end
  end

  def render_owner_apartments
    my_apartments = Apartment.all.where(agent_id: @user.id)

    if my_apartments.count.positive?
      content_tag :div, class: 'current-user-aparments' do
        heading = render_onwner_heading

        apartments_list = content_tag :div do
          my_apartments.each do |rental|
            photos_container = content_tag :div, class: 'apartmentphotos-frame' do
              rental.apartment_attachments.count.positive? &&
                rental.apartment_attachments[0..1].each do |pic|
                  pic.apartmentphoto.url && concat(cl_image_tag(pic.apartmentphoto.url, width: 300,
                    height: 100, fetch_format: :auto, quality: 'auto',
                    use_root_path: true, class: 'apartment-image'))
                end
            end

            apartment_details = render_apartment_details(rental)

            concat(photos_container + apartment_details)
          end
        end
        concat(heading + apartments_list)
      end
    else
      render_no_apartments_info(my_apartments)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # USER SHOW PAGE RIGHTBAR
  def user_followers
    followers_array = @user.inverse_followings.map do |following|
      User.all.where(id: following.follower_id).includes(:followings)
    end

    content_tag :ul, class: 'user-followers' do
      followers_array[0..5].each do |user|
        follower_row = link_to(user_path(user[0])) do
          content_tag :li, class: 'who-to-follow-item' do
            if user[0].avatar.url.present?
              user_icon = content_tag(cl_image_tag(user[0].avatar, width: 50, height: 50,
                                                                   fetch_format: :auto, quality: 'auto',
                                                                   use_root_path: true, class: 'user-followers-avatar'))
            else
              user_icon = content_tag :i, class: 'fas fa-user-circle user-icon' do; end
            end

            follower_details = content_tag :div, class: 'user-followers-details' do
              follower_fullname = content_tag(:p, user[0].fullname,
                                              class: 'user-followers-fullname')
              follower_followers = content_tag(:small,
                                               "#{user[0].inverse_followings.count} followers",
                                               class: 'user-followers-fullname')

              follower_fullname + follower_followers
            end

            user_icon + follower_details
          end
        end

        concat(follower_row)
      end
    end
  end

  def render_coverimage_zone_avatar(user)
    if user && user.avatar.url.present?
      content_tag :div do
        cl_image_tag(user.avatar.url, width: 88, height: 88,
                                      fetch_format: :auto, quality: 'auto',
                                      use_root_path: true,
                                      class: 'user-show-avatar')
      end
    else
      content_tag :div do
        content_tag :i, class: 'fas fa-user-circle user-icon' do; end
      end
    end
  end

  def render_sidebar_followers
    return unless current_user

    if current_user
      content_tag :div, class: 'followers-zone' do
        followings_div = content_tag :div do
          followings_count = content_tag(:h2, current_user.followings.count.to_s)
          label_followings = content_tag(:p, 'Following')

          followings_count + label_followings
        end

        followers_div = content_tag :div do
          followers_count = content_tag(:h2, current_user.inverse_followings.count.to_s)
          label_followers = content_tag(:p, 'Followers')

          followers_count + label_followers
        end

        concat(followings_div + followers_div)
      end
    end
  end

  # USERS INDEX PAGE
  def avatar_present?(user)
    if user.avatar.url.present?
      content_tag :div do
        cl_image_tag(user.avatar.url, width: 60, height: 60,
                                      fetch_format: :auto, quality: 'auto', use_root_path: true,
                                      class: 'users-list-avatar')
      end
    else
      content_tag(:i, class: 'fa fa-user-circle user-icon') { ; }
    end
  end

  def render_user_details(user)
    content_tag :div, class: 'who-to-follow-details' do
      user_fullname = content_tag :p do
        content_tag(:strong, user.fullname.to_s)
      end
      user_followerz = content_tag(:small, "#{user.inverse_followings.count} followers")

      user_fullname + user_followerz
    end
  end

  # Mobile page WHO TO FOLLOW (users#index)
  def who_to_follow
    content_tag :ul do
      User.all.ordered_by_most_recent[0..6].each do |user|
        next unless user != current_user && !current_user_followers.include?(user.id)

        user_row_link = link_to user_path(user), class: 'who-to-follow-link' do
          content_tag :li, class: 'who-to-follow-item users-index-wtf-item' do
            user_icon = avatar_present?(user)
            user_details = render_user_details(user)

            user_icon + user_details
          end
        end

        concat(user_row_link)
      end
    end
  end
end

app/views/users/_coverimage_zone.html.erb
<div class="cover-image-container">
  <%= render_coverphoto %>

  <div class="show-user-details">
    <div class="user-show-avatar-zone">
      <div class="show-avatar-wrapper">
          <div>
              <%= render_follow_btn %>
              <p class="flex-spacer"></p>
          </div>
          
          <%= render_coverimage_zone_avatar(@user) %>

          <div>
            <% if @user && @user != current_user %>
              <%= link_to user_reviews_path(@user, @reviews) do %>
                <button class="btn-review-cover-img">Add Review</button>
              <% end %>
            <% end %>
          </div> 
      </div>

      <div>
        <h4><%= render_userpage_fullname %></h4>
        <small>@<%= render_userpage_username %></small>
      </div>
    </div>

    <div class="dashbord-followers-zone">
      <div>
        <%= render_userpage_reviews_link %>
      </div>
      <%= render_userpage_followings %>
      <%= render_userpage_followers %>
    </div>
  </div>
</div>

app/views/users/_user_rightbar.html.erb
<div class="user_rightbar">
  <h4 class="right-bar-header">
    <span>FOLLOWED BY</span>
  </h4>

  <%= user_followers %>
</div>

app/views/users/_user_sub_topbar.html.erb
<div class="user-page-smaller_topbar">
  <a href=""></a>
  <div data-controller="toggler" class="smaller-topbar-link user-page-ap-form">
    <button
      class="btn-data-action-new-apartment"
      data-action="click->toggler#opencanvas"
    >ADD NEW APARTMENT</button>
      <span data-target="toggler.canvas" class="d-none">
        <%= render 'apartments/apartment_form' %>
      </span>
  </div>
  <div class = "smaller-topbar-link" >
    <i class="fa fa-envelope envelope-icon"></i>propsuite@domain.com
  </div>
  <%= link_to "SEARCH APARTMENTS", new_search_path, class: "smaller-topbar-link" %>
</div>

app/views/users/index.html.erb
<div class = "primary-container">
  <div class="primary-main">

    <h1>WHO TO FOLLOW</h1>
    <small>
      <span class="search-asterist">*</span>
      click on any row to view user details
    </small>

    <div class="usersindex-who-to-follow-wrapper">
      <%= who_to_follow %>
    </div>
  </div>
<div>

app/views/users/show.html.erb
<div>
  <%= render 'navbar/navbar' %>
  <%= render 'layouts/sidebar' %>
  <%= render 'coverimage_zone' %>
  
  <main class="user-details-container">
    <div class="details-wrapper">
      <div class="main-user-details-showcase">
        <%= render 'user_sub_topbar' %>
        <%= render_owner_apartments %>
      </div>

    </div>
    <%= render 'user_rightbar' %>
  </main>
</div>