config/routes.rb
Rails.application.routes.draw do
  root 'apartments#index'
  
  devise_for :users
  resources :reviews
  resources :users, only: [:index, :show] do
    resources :reviews, only: [:create, :show, :index]
  end
  resources :apartments
  resources :searches, only: [:new, :create, :show]
  resources :followings, only: [:new, :index, :show, :create]
end

app/views/layouts/_how.html.erb
<ul class="how-it-works-wrapper">
  <h2>HOW IT WORKS</h2>
  <li>A seller(agent) posts an available apartment.</li>
  <li>Registered and unregistered clients can view the apartments and the poster's details.</li>
  <li>Interested clients can contact the agent that posted the apartment or DM them.</li>
  <li>After their transaction the user that bought the apartment can then review the seller with ratings and 
  comments.</li>
  <li>But, only registered clients can review a seller.</li>
</ul>

app/views/layouts/_mobile_sidebar.html.erb
<div class="mobile-sidebar-container">
  <%= render_mobile_sidebar_currentuser_avatar %>

  <%= mobile_followers_zone %>

  <div class="nav-zone">
    <ul>
      <%= render_home_link %>
      <%= render_who_to_follow_link %>
      <%= render_profile_link %>
      <%= render_dashboard_link %>
      <%= render_owner_apartments_link %>
      <%= render_logout_link %>
    </ul>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar-container">
  <div class="avatar-zone">
    <%= render_currentuser_avatar_link %>    
    <%= render_current_usernames %>
  </div>

  <%= render_sidebar_followers %>

  <div class="nav-zone">
    <ul>
      <%= render_home_link %>
      <%= render_profile_link %>
      <%= render_dashboard_link %>
      <%= render_owner_apartments_link %>
    </ul>
  </div>
</div>

app/views/layouts/_smaller_topbar.html.erb
<div class="smaller-topbar">
  <div data-controller="toggler" class= "smaller-topbar-link">
    <button
      class="btn-data-action-new-apartment"
      data-action="click->toggler#opencanvas"
    >ADD NEW APARTMENT</button>
      <span data-target="toggler.canvas" class="d-none">
        <%= render 'apartment_form' %>
      </span>
  </div>
  <%= link_to 'LATEST DEALS', apartments_path, class: "smaller-topbar-link" %>
  <div data-controller="toggler" class="smaller-topbar-link">
    <button
      class="btn-hiw-link"
      data-action="click->toggler#opencanvas"
    >HOW IT WORKS</button>
      <span data-target="toggler.canvas" class="d-none">
        <%= render 'layouts/how' %>
      </span>
  </div>
  <div class = "smaller-topbar-link" ><i class="fa fa-envelope envelope-icon"></i>propsuite@domain.com</div>
  <%= link_to "SEARCH APARTMENTS", new_search_path, class: "smaller-topbar-link" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropSuite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Montserrat&display=swap"
    />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,700;0,900;1,300;1,400&display=swap"
     rel="stylesheet">
    
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300;400;700&display=swap"
     rel="stylesheet">
    <script
      src="https://kit.fontawesome.com/5a1759509c.js"
      crossorigin="anonymous"
    ></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render 'navbar/mobile_nav' %>
    </div>
      <%= render_flash_messages %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', async: true %>
    <%= yield %>
  </body>
</html>